@echo off
REM Copies the required DLLs from your BepInEx game installation into lib/
REM The game must have been launched at least once with BepInEx so the
REM interop DLLs are generated.

echo Setting up build environment...
echo.

if not exist "lib" mkdir lib

REM ── Auto-detect game path ────────────────────────────────────────────────
set "GAME_PATH="

for %%D in (C: D: E: F: G: H: I: J: K: L: M: N: O: P: Q: R: S: T: U: V: W: X: Y: Z:) do (
    if exist "%%D\SteamLibrary\steamapps\common\Flipping is Hard Demo\BepInEx\interop" (
        set "GAME_PATH=%%D\SteamLibrary\steamapps\common\Flipping is Hard Demo"
        goto found
    )
    if exist "%%D\Program Files\Steam\steamapps\common\Flipping is Hard Demo\BepInEx\interop" (
        set "GAME_PATH=%%D\Program Files\Steam\steamapps\common\Flipping is Hard Demo"
        goto found
    )
    if exist "%%D\Program Files (x86)\Steam\steamapps\common\Flipping is Hard Demo\BepInEx\interop" (
        set "GAME_PATH=%%D\Program Files (x86)\Steam\steamapps\common\Flipping is Hard Demo"
        goto found
    )
)

:found
if "%GAME_PATH%"=="" (
    echo ERROR: Game not found.
    echo.
    echo Make sure:
    echo   1. "Flipping is Hard Demo" is installed via Steam
    echo   2. BepInEx 6 is installed in the game folder
    echo   3. You have launched the game at least once with BepInEx
    echo      ^(this generates the BepInEx\interop\ folder^)
    echo.
    echo If your Steam library is in a non-standard location, edit this file
    echo and set GAME_PATH manually at the top.
    pause
    exit /b 1
)

echo Found game at: %GAME_PATH%
echo.

REM ── BepInEx core DLLs ───────────────────────────────────────────────────
echo Copying BepInEx core DLLs...
for %%F in (BepInEx.Core.dll BepInEx.Unity.Common.dll BepInEx.Unity.IL2CPP.dll Il2CppInterop.Runtime.dll) do (
    if exist "%GAME_PATH%\BepInEx\core\%%F" (
        copy /Y "%GAME_PATH%\BepInEx\core\%%F" "lib\" >nul
        echo   OK  %%F
    ) else (
        echo   MISSING  %%F
    )
)

REM ── Unity interop DLLs (generated by BepInEx) ───────────────────────────
echo.
echo Copying Unity interop DLLs...
for %%F in (UnityEngine.dll UnityEngine.CoreModule.dll UnityEngine.IMGUIModule.dll UnityEngine.InputLegacyModule.dll UnityEngine.PhysicsModule.dll UnityEngine.TextRenderingModule.dll Il2Cppmscorlib.dll) do (
    if exist "%GAME_PATH%\BepInEx\interop\%%F" (
        copy /Y "%GAME_PATH%\BepInEx\interop\%%F" "lib\" >nul
        echo   OK  %%F
    ) else (
        echo   MISSING  %%F
    )
)

echo.
if exist "lib\UnityEngine.CoreModule.dll" (
    echo Setup complete. Run build.bat to compile.
) else (
    echo Setup FAILED. Check errors above.
    pause
    exit /b 1
)
